# Generated by Django 4.2.4 on 2023-08-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.TextField(default='Nada ha pasado'),
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default='2000-12-13'),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(max_length=200),
        ),
    ]
